apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../canary
patches:
  - path: transaction-api-rollback-patch.yaml
  - path: canary-threshold-patch.yaml
images:
  - name: transaction-api
    newName: transaction-api
    newTag: local
  - name: ledger-service
    newName: ledger-service
    newTag: local
  - name: receipt-worker
    newName: receipt-worker
    newTag: local
