apiVersion: v1
kind: Service
metadata:
  name: receipt-worker
  labels:
    app.kubernetes.io/name: receipt-worker
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: belo
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: receipt-worker
  ports:
    - name: http
      port: 3002
      targetPort: http
