apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: receipt-worker
  labels:
    app.kubernetes.io/name: receipt-worker
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: belo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: receipt-worker
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
