apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-service
  labels:
    app.kubernetes.io/name: ledger-service
    app.kubernetes.io/component: ledger
    app.kubernetes.io/part-of: belo
    app.kubernetes.io/version: stable
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ledger-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ledger-service
        app.kubernetes.io/component: ledger
        app.kubernetes.io/part-of: belo
        app.kubernetes.io/version: stable
    spec:
      containers:
        - name: ledger-service
          image: ledger-service:local
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3001"
            - name: SERVICE_VERSION
              value: stable
            - name: GIT_COMMIT
              value: local
          ports:
            - name: http
              containerPort: 3001
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 65532
            runAsGroup: 65532
            capabilities:
              drop:
                - ALL
