apiVersion: v1
kind: Service
metadata:
  name: ministack
  labels:
    app.kubernetes.io/name: ministack
    app.kubernetes.io/component: sqs-emulator
    app.kubernetes.io/part-of: belo
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ministack
  ports:
    - name: http
      port: 4566
      targetPort: http
