AWSTemplateFormatVersion: "2010-09-09"
Description: >
  This template implements an IAM user 'Messi'
  An S3 bucket for dog pictues
  An S3 bucket for other cats
  And permissions appropriate for Messi.
Parameters:
  messipassword:
    NoEcho: true
    Description: IAM User Messi's Password - Must contain at least 8 characters with uppercase, lowercase, number, and symbol
    Type: String
    AllowedPattern: '(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^\w\s]).{8,}'
    ConstraintDescription: Password must be at least 8 characters long and contain at least one uppercase letter, one lowercase letter, one number, and one symbol
Resources:
  dogpics:
    Type:  AWS::S3::Bucket
  catpics:
    Type:  AWS::S3::Bucket
  messi:
    Type: AWS::IAM::User
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/IAMUserChangePassword
      LoginProfile:
        Password: !Ref messipassword
        PasswordResetRequired: "true"
  AppAccessS3Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AppAccessS3Role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Ref policy
  policy:
    Type: AWS::IAM::ManagedPolicy
    Properties: 
      Description: Allow access to all S3 buckets, except dogpics
      ManagedPolicyName: AllowAllS3ExceptDogs
      PolicyDocument: 
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: 's3:*'
            Resource: '*' 
          - Effect: Deny
            Action: 's3:*'
            Resource: [ !GetAtt dogpics.Arn, !Join ['', [!GetAtt dogpics.Arn, '/*']]]
Outputs:
  dogpicsbucketname:
    Description: Bucketname for dogpictures (the best animal btw)
    Value: !Ref dogpics
  catpicsbucketname:
    Description: Bucketname for catpics
    Value: !Ref catpics
  messiusername:
    Description: IAM Username for Messi
    Value: !Ref messi
  AppAccessS3RoleArn:
    Description: ARN of the AppAccessS3Role role
    Value: !GetAtt AppAccessS3Role.Arn