apiVersion: v1
kind: Secret
metadata:
  name: sqs-credentials
  labels:
    app.kubernetes.io/name: sqs-credentials
    app.kubernetes.io/component: transport
    app.kubernetes.io/part-of: belo
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: test
  AWS_SECRET_ACCESS_KEY: test
