apiVersion: v1
kind: ConfigMap
metadata:
  name: sqs-config
  labels:
    app.kubernetes.io/name: sqs-config
    app.kubernetes.io/component: transport
    app.kubernetes.io/part-of: belo
data:
  AWS_REGION: us-east-1
  AWS_ENDPOINT_URL: http://ministack.ministack.svc.cluster.local:4566
  SQS_QUEUE_RECEIPT_COMMANDS: receipt-commands
  SQS_QUEUE_URL: http://ministack.ministack.svc.cluster.local:4566/000000000000/receipt-commands
