apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: transaction-api
  labels:
    app.kubernetes.io/name: transaction-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: belo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: transaction-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
