project_id = "tu-proyecto-id"
region     = "us-central1"
zone       = "us-central1-a"
microservice_name = "shopping-experience"
vm_name = "pipeline-vm"
vm_machine_type = "e2-micro"
ssh_private_key_path  = "/Users/eduardo/repos/isw2/demo-cloud/cloudcomputing-demo/fiuba-demo.pem"
ssh_public_key_path   = "/Users/eduardo/repos/isw2/demo-cloud/cloudcomputing-demo/fiuba-demo.pub"
allowed_ip_cidr       = "0.0.0.0/0"  # o tu IP pública por seguridad
